<?
$Fritzbox_FunctionsVars=array(
   "WANCommonInterfaceConfig"=>array(
      "GetCommonLinkProperties"=>array(
         "NewWANAccessType"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>'DSL|POTS|Cable|Ethernet|Other',
            "typ"=>'string'
         ),
         "NewLayer1UpstreamMaxBitRate"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "NewLayer1DownstreamMaxBitRate"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "NewPhysicalLinkStatus"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>'Up|Down|Initializing|Unavailable',
            "typ"=>'string'
         )
      ),
      "GetTotalBytesSent"=>array(
         "NewTotalBytesSent"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         )
      ),
      "GetTotalBytesReceived"=>array(
         "NewTotalBytesReceived"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         )
      ),
      "GetTotalPacketsSent"=>array(
         "NewTotalPacketsSent"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         )
      ),
      "GetTotalPacketsReceived"=>array(
         "NewTotalPacketsReceived"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         )
      ),
      "GetAddonInfos"=>array(
         "NewByteSendRate"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "NewByteReceiveRate"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "NewPacketSendRate"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "NewPacketReceiveRate"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "NewTotalBytesSent"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "NewTotalBytesReceived"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "NewAutoDisconnectTime"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "NewIdleDisconnectTime"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "NewDNSServer1"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "NewDNSServer2"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "NewVoipDNSServer1"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "NewVoipDNSServer2"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "NewUpnpControlEnabled"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         ),
         "NewRoutedBridgedModeBoth"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui1'
         )
      )
   ),
   "WANDSLLinkConfig"=>array(
      "SetDSLLinkType"=>array(
         "NewLinkType"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>'EoA|IPoA|CIP|PPPoA|PPPoE|Unconfigured',
            "typ"=>'string'
         )
      ),
      "GetDSLLinkInfo"=>array(
         "NewLinkType"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>'EoA|IPoA|CIP|PPPoA|PPPoE|Unconfigured',
            "typ"=>'string'
         ),
         "NewLinkStatus"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>'Up|Down|Initializing|Unavailable',
            "typ"=>'string'
         )
      ),
      "GetAutoConfig"=>array(
         "NewAutoConfig"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         )
      ),
      "GetModulationType"=>array(
         "NewModulationType"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>'ADSL G.lite|G.shdsl|IDSL|HDSL|SDSL|VDSL',
            "typ"=>'string'
         )
      ),
      "SetDestinationAddress"=>array(
         "NewDestinationAddress"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "GetDestinationAddress"=>array(
         "NewDestinationAddress"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "SetATMEncapsulation"=>array(
         "NewATMEncapsulation"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>'LLC|VCMUX',
            "typ"=>'string'
         )
      ),
      "GetATMEncapsulation"=>array(
         "NewATMEncapsulation"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>'LLC|VCMUX',
            "typ"=>'string'
         )
      ),
      "SetFCSPreserved"=>array(
         "NewFCSPreserved"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         )
      ),
      "GetFCSPreserved"=>array(
         "NewFCSPreserved"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         )
      )
   ),
   "WANIPConnection"=>array(
      "SetConnectionType"=>array(
         "NewConnectionType"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "GetConnectionTypeInfo"=>array(
         "NewConnectionType"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "NewPossibleConnectionTypes"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>'Unconfigured|IP_Routed|IP_Bridged',
            "typ"=>'string'
         )
      ),
      "RequestConnection"=>null,
      "ForceTermination"=>null,
      "GetStatusInfo"=>array(
         "NewConnectionStatus"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>'Unconfigured|Connecting|Authenticating|PendingDisconnect|Disconnecting|Disconnected|Connected',
            "typ"=>'string'
         ),
         "NewLastConnectionError"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>'ERROR_NONE|ERROR_ISP_TIME_OUT|ERROR_COMMAND_ABORTED|ERROR_NOT_ENABLED_FOR_INTERNET|ERROR_BAD_PHONE_NUMBER|ERROR_USER_DISCONNECT|ERROR_ISP_DISCONNECT|ERROR_IDLE_DISCONNECT|ERROR_FORCED_DISCONNECT|ERROR_SERVER_OUT_OF_RESOURCES|ERROR_RESTRICTED_LOGON_HOURS|ERROR_ACCOUNT_DISABLED|ERROR_ACCOUNT_EXPIRED|ERROR_PASSWORD_EXPIRED|ERROR_AUTHENTICATION_FAILURE|ERROR_NO_DIALTONE|ERROR_NO_CARRIER|ERROR_NO_ANSWER|ERROR_LINE_BUSY|ERROR_UNSUPPORTED_BITSPERSECOND|ERROR_TOO_MANY_LINE_ERRORS|ERROR_IP_CONFIGURATION|ERROR_UNKNOWN',
            "typ"=>'string'
         ),
         "NewUptime"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         )
      ),
      "GetNATRSIPStatus"=>array(
         "NewRSIPAvailable"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         ),
         "NewNATEnabled"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         )
      ),
      "GetGenericPortMappingEntry"=>array(
         "NewPortMappingIndex"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui2'
         ),
         "NewRemoteHost"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "NewExternalPort"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui2'
         ),
         "NewProtocol"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>'TCP|UDP',
            "typ"=>'string'
         ),
         "NewInternalPort"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui2'
         ),
         "NewInternalClient"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "NewEnabled"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         ),
         "NewPortMappingDescription"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "NewLeaseDuration"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         )
      ),
      "GetSpecificPortMappingEntry"=>array(
         "NewRemoteHost"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "NewExternalPort"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui2'
         ),
         "NewProtocol"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>'TCP|UDP',
            "typ"=>'string'
         ),
         "NewInternalPort"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui2'
         ),
         "NewInternalClient"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "NewEnabled"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         ),
         "NewPortMappingDescription"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "NewLeaseDuration"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         )
      ),
      "AddPortMapping"=>array(
         "NewRemoteHost"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "NewExternalPort"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui2'
         ),
         "NewProtocol"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>'TCP|UDP',
            "typ"=>'string'
         ),
         "NewInternalPort"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui2'
         ),
         "NewInternalClient"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "NewEnabled"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         ),
         "NewPortMappingDescription"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "NewLeaseDuration"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         )
      ),
      "DeletePortMapping"=>array(
         "NewRemoteHost"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "NewExternalPort"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui2'
         ),
         "NewProtocol"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>'TCP|UDP',
            "typ"=>'string'
         )
      ),
      "GetExternalIPAddress"=>array(
         "NewExternalIPAddress"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      )
   ),
   "FritzboxUpnpClass"=>array(
      "__construct"=>array(
         "BASE"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'object'
         ),
         "SERVICE"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "SERVICEURL"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "EVENTURL"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "RegisterEventCallback"=>array(
         "callback_url"=>array(
            "mode"=>'in',
            "default"=>'',
            "allowed"=>null,
            "typ"=>'string'
         ),
         "timeout"=>array(
            "mode"=>'in',
            "default"=>'3600',
            "allowed"=>null,
            "typ"=>'int'
         ),
         "SID"=>array(
            "mode"=>'out',
            "default"=>'',
            "allowed"=>null,
            "typ"=>'string'
         ),
         "TIMEOUT"=>array(
            "mode"=>'out',
            "default"=>'',
            "allowed"=>null,
            "typ"=>'int'
         ),
         "Server"=>array(
            "mode"=>'out',
            "default"=>'',
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "UnRegisterEventCallback"=>array(
         "SID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      )
   ),
   "FritzboxXmlRpcDevice"=>array(
      "__construct"=>array(
         "url"=>array(
            "mode"=>'in',
            "default"=>'',
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "Upnp"=>array(
         "url"=>array(
            "mode"=>'in',
            "default"=>'',
            "allowed"=>null,
            "typ"=>'string'
         ),
         "SOAP_service"=>array(
            "mode"=>'in',
            "default"=>'',
            "allowed"=>null,
            "typ"=>'string'
         ),
         "SOAP_action"=>array(
            "mode"=>'in',
            "default"=>'',
            "allowed"=>null,
            "typ"=>'string'
         ),
         "SOAP_arguments"=>array(
            "mode"=>'in',
            "default"=>'',
            "allowed"=>null,
            "typ"=>'string'
         ),
         "XML_filter"=>array(
            "mode"=>'in',
            "default"=>'',
            "allowed"=>null,
            "typ"=>'string'
         ),
         "result"=>array(
            "mode"=>'out',
            "default"=>'',
            "allowed"=>null,
            "typ"=>'string|array'
         )
      ),
      "Filter"=>array(
         "subject"=>array(
            "mode"=>'in',
            "default"=>'',
            "allowed"=>null,
            "typ"=>'string'
         ),
         "pattern"=>array(
            "mode"=>'in',
            "default"=>'',
            "allowed"=>null,
            "typ"=>'string|stringlist|array of strings'
         ),
         "result"=>array(
            "mode"=>'out',
            "default"=>'',
            "allowed"=>null,
            "typ"=>'variant'
         )
      )
   )
);
?>