<?
$Sonos_FunctionsVars=array(
   "AlarmClock"=>array(
      "SetFormat"=>array(
         "DesiredTimeFormat"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "DesiredDateFormat"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "GetFormat"=>array(
         "CurrentTimeFormat"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "CurrentDateFormat"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "SetTimeZone"=>array(
         "Index"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'i4'
         ),
         "AutoAdjustDst"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         )
      ),
      "GetTimeZone"=>array(
         "Index"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'i4'
         ),
         "AutoAdjustDst"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         )
      ),
      "GetTimeZoneAndRule"=>array(
         "Index"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'i4'
         ),
         "AutoAdjustDst"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         ),
         "CurrentTimeZone"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "GetTimeZoneRule"=>array(
         "Index"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'i4'
         ),
         "TimeZone"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "SetTimeServer"=>array(
         "DesiredTimeServer"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "GetTimeServer"=>array(
         "CurrentTimeServer"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "SetTimeNow"=>array(
         "DesiredTime"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "TimeZoneForDesiredTime"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "GetHouseholdTimeAtStamp"=>array(
         "TimeStamp"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "HouseholdUTCTime"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "GetTimeNow"=>array(
         "CurrentUTCTime"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "CurrentLocalTime"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "CurrentTimeZone"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "CurrentTimeGeneration"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         )
      ),
      "CreateAlarm"=>array(
         "StartLocalTime"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "Duration"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "Recurrence"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>'ONCE|WEEKDAYS|WEEKENDS|DAILY',
            "typ"=>'string'
         ),
         "Enabled"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         ),
         "RoomUUID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "ProgramURI"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "ProgramMetaData"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "PlayMode"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>'NORMAL|REPEAT_ALL|SHUFFLE_NOREPEAT|SHUFFLE',
            "typ"=>'string'
         ),
         "Volume"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui2'
         ),
         "IncludeLinkedZones"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         ),
         "AssignedID"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         )
      ),
      "UpdateAlarm"=>array(
         "ID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "StartLocalTime"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "Duration"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "Recurrence"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>'ONCE|WEEKDAYS|WEEKENDS|DAILY',
            "typ"=>'string'
         ),
         "Enabled"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         ),
         "RoomUUID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "ProgramURI"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "ProgramMetaData"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "PlayMode"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>'NORMAL|REPEAT_ALL|SHUFFLE_NOREPEAT|SHUFFLE',
            "typ"=>'string'
         ),
         "Volume"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui2'
         ),
         "IncludeLinkedZones"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         )
      ),
      "DestroyAlarm"=>array(
         "ID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         )
      ),
      "ListAlarms"=>array(
         "CurrentAlarmList"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "CurrentAlarmListVersion"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "SetDailyIndexRefreshTime"=>array(
         "DesiredDailyIndexRefreshTime"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "GetDailyIndexRefreshTime"=>array(
         "CurrentDailyIndexRefreshTime"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      )
   ),
   "MusicServices"=>array(
      "GetSessionId"=>array(
         "ServiceId"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'i2'
         ),
         "Username"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "SessionId"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "ListAvailableServices"=>array(
         "AvailableServiceDescriptorList"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "AvailableServiceTypeList"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "AvailableServiceListVersion"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "UpdateAvailableServices"=>null
   ),
   "DeviceProperties"=>array(
      "SetLEDState"=>array(
         "DesiredLEDState"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>'On|Off',
            "typ"=>'string'
         )
      ),
      "GetLEDState"=>array(
         "CurrentLEDState"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>'On|Off',
            "typ"=>'string'
         )
      ),
      "AddBondedZones"=>array(
         "ChannelMapSet"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "RemoveBondedZones"=>array(
         "ChannelMapSet"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "CreateStereoPair"=>array(
         "ChannelMapSet"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "SeparateStereoPair"=>array(
         "ChannelMapSet"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "SetZoneAttributes"=>array(
         "DesiredZoneName"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "DesiredIcon"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "DesiredConfiguration"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "GetZoneAttributes"=>array(
         "CurrentZoneName"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "CurrentIcon"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "CurrentConfiguration"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "GetHouseholdID"=>array(
         "CurrentHouseholdID"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "GetZoneInfo"=>array(
         "SerialNumber"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "SoftwareVersion"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "DisplaySoftwareVersion"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "HardwareVersion"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "IPAddress"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "MACAddress"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "CopyrightInfo"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "ExtraInfo"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "HTAudioIn"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         )
      ),
      "SetAutoplayLinkedZones"=>array(
         "IncludeLinkedZones"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         )
      ),
      "GetAutoplayLinkedZones"=>array(
         "IncludeLinkedZones"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         )
      ),
      "SetAutoplayRoomUUID"=>array(
         "RoomUUID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "GetAutoplayRoomUUID"=>array(
         "RoomUUID"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "SetAutoplayVolume"=>array(
         "Volume"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui2'
         )
      ),
      "GetAutoplayVolume"=>array(
         "CurrentVolume"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui2'
         )
      ),
      "ImportSetting"=>array(
         "SettingID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "SettingURI"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "SetUseAutoplayVolume"=>array(
         "UseVolume"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         )
      ),
      "GetUseAutoplayVolume"=>array(
         "UseVolume"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         )
      ),
      "AddHTSatellite"=>array(
         "HTSatChanMapSet"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "RemoveHTSatellite"=>array(
         "SatRoomUUID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      )
   ),
   "SystemProperties"=>array(
      "SetString"=>array(
         "VariableName"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "StringValue"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "SetStringX"=>array(
         "VariableName"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "StringValue"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "GetString"=>array(
         "VariableName"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "StringValue"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "GetStringX"=>array(
         "VariableName"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "StringValue"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "Remove"=>array(
         "VariableName"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "RemoveX"=>array(
         "VariableName"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "GetWebCode"=>array(
         "AccountType"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "WebCode"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "ProvisionTrialAccount"=>array(
         "AccountType"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "AccountUDN"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "ProvisionCredentialedTrialAccountX"=>array(
         "AccountType"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "AccountID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "AccountPassword"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "IsExpired"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         ),
         "AccountUDN"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "MigrateTrialAccountX"=>array(
         "TargetAccountType"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "TargetAccountID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "TargetAccountPassword"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "AddAccountX"=>array(
         "AccountType"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "AccountID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "AccountPassword"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "AccountUDN"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "AddAccountWithCredentialsX"=>array(
         "AccountType"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "AccountToken"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "AccountKey"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "AddOAuthAccountX"=>array(
         "AccountType"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "AccountToken"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "AccountKey"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "OAuthDeviceID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "AccountUDN"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "RemoveAccount"=>array(
         "AccountType"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "AccountID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "EditAccountPasswordX"=>array(
         "AccountType"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "AccountID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "NewAccountPassword"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "SetAccountNicknameX"=>array(
         "AccountUDN"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "AccountNickname"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "RefreshAccountCredentialsX"=>array(
         "AccountType"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "AccountUID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "AccountToken"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "AccountKey"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "EditAccountMd"=>array(
         "AccountType"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "AccountID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "NewAccountMd"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "DoPostUpdateTasks"=>null,
      "ResetThirdPartyCredentials"=>null,
      "EnableRDM"=>array(
         "RDMValue"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         )
      ),
      "GetRDM"=>array(
         "RDMValue"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         )
      ),
      "ReplaceAccountX"=>array(
         "AccountUDN"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "NewAccountID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "NewAccountPassword"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "NewAccountUDN"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      )
   ),
   "ZoneGroupTopology"=>array(
      "CheckForUpdate"=>array(
         "UpdateType"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>'All|Software',
            "typ"=>'string'
         ),
         "CachedOnly"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         ),
         "Version"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "UpdateItem"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "BeginSoftwareUpdate"=>array(
         "UpdateURL"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "Flags"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "ExtraOptions"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "ReportUnresponsiveDevice"=>array(
         "DeviceUUID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "DesiredAction"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>'Remove|VerifyThenRemoveSystemwide',
            "typ"=>'string'
         )
      ),
      "ReportAlarmStartedRunning"=>null,
      "SubmitDiagnostics"=>array(
         "DiagnosticID"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "IncludeControllers"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         ),
         "Type"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>'Healthcheck|Server|User',
            "typ"=>'string'
         )
      ),
      "RegisterMobileDevice"=>array(
         "MobileDeviceName"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "MobileDeviceUDN"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "MobileIPAndPort"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "GetZoneGroupAttributes"=>array(
         "CurrentZoneGroupName"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "CurrentZoneGroupID"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "CurrentZonePlayerUUIDsInGroup"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "GetZoneGroupState"=>array(
         "ZoneGroupState"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      )
   ),
   "GroupManagement"=>array(
      "AddMember"=>array(
         "MemberID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "CurrentTransportSettings"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "GroupUUIDJoined"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "ResetVolumeAfter"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         ),
         "VolumeAVTransportURI"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "RemoveMember"=>array(
         "MemberID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "ReportTrackBufferingResult"=>array(
         "MemberID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "ResultCode"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'i4'
         )
      )
   ),
   "QPlay"=>array(
      "QPlayAuth"=>array(
         "Seed"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "Code"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "MID"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "DID"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      )
   ),
   "ContentDirectory"=>array(
      "GetSearchCapabilities"=>array(
         "SearchCaps"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "GetSortCapabilities"=>array(
         "SortCaps"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "GetSystemUpdateID"=>array(
         "Id"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         )
      ),
      "GetAlbumArtistDisplayOption"=>array(
         "AlbumArtistDisplayOption"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "GetLastIndexChange"=>array(
         "LastIndexChange"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "Browse"=>array(
         "ObjectID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "BrowseFlag"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>'BrowseMetadata|BrowseDirectChildren',
            "typ"=>'string'
         ),
         "Filter"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "StartingIndex"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "RequestedCount"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "SortCriteria"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "Result"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "NumberReturned"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "TotalMatches"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "UpdateID"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         )
      ),
      "FindPrefix"=>array(
         "ObjectID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "Prefix"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "StartingIndex"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "UpdateID"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         )
      ),
      "GetAllPrefixLocations"=>array(
         "ObjectID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "TotalPrefixes"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "PrefixAndIndexCSV"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "UpdateID"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         )
      ),
      "CreateObject"=>array(
         "ContainerID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "Elements"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "ObjectID"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "Result"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "UpdateObject"=>array(
         "ObjectID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "CurrentTagValue"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "NewTagValue"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "DestroyObject"=>array(
         "ObjectID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "RefreshShareList"=>null,
      "RefreshShareIndex"=>array(
         "AlbumArtistDisplayOption"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "RequestResort"=>array(
         "SortOrder"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "GetShareIndexInProgress"=>array(
         "IsIndexing"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         )
      ),
      "GetBrowseable"=>array(
         "IsBrowseable"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         )
      ),
      "SetBrowseable"=>array(
         "Browseable"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         )
      )
   ),
   "ConnectionManager"=>array(
      "GetProtocolInfo"=>array(
         "Source"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "Sink"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "GetCurrentConnectionIDs"=>array(
         "ConnectionIDs"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "GetCurrentConnectionInfo"=>array(
         "ConnectionID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'i4'
         ),
         "RcsID"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'i4'
         ),
         "AVTransportID"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'i4'
         ),
         "ProtocolInfo"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "PeerConnectionManager"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "PeerConnectionID"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'i4'
         ),
         "Direction"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>'Input|Output',
            "typ"=>'string'
         ),
         "Status"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>'OK|ContentFormatMismatch|InsufficientBandwidth|UnreliableChannel|Unknown',
            "typ"=>'string'
         )
      )
   ),
   "RenderingControl"=>array(
      "GetMute"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "Channel"=>array(
            "mode"=>'in',
            "default"=>''Master'',
            "allowed"=>'Master|LF|RF|SpeakerOnly',
            "typ"=>'string'
         ),
         "CurrentMute"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         )
      ),
      "SetMute"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "Channel"=>array(
            "mode"=>'in',
            "default"=>''Master'',
            "allowed"=>'Master|LF|RF|SpeakerOnly',
            "typ"=>'string'
         ),
         "DesiredMute"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         )
      ),
      "ResetBasicEQ"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "Bass"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'i2'
         ),
         "Treble"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'i2'
         ),
         "Loudness"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         ),
         "LeftVolume"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui2'
         ),
         "RightVolume"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui2'
         )
      ),
      "ResetExtEQ"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "EQType"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "GetVolume"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "Channel"=>array(
            "mode"=>'in',
            "default"=>''Master'',
            "allowed"=>'Master|LF|RF',
            "typ"=>'string'
         ),
         "CurrentVolume"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui2'
         )
      ),
      "SetVolume"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "Channel"=>array(
            "mode"=>'in',
            "default"=>''Master'',
            "allowed"=>'Master|LF|RF',
            "typ"=>'string'
         ),
         "DesiredVolume"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui2'
         )
      ),
      "SetRelativeVolume"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "Channel"=>array(
            "mode"=>'in',
            "default"=>''Master'',
            "allowed"=>'Master|LF|RF',
            "typ"=>'string'
         ),
         "Adjustment"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'i4'
         ),
         "NewVolume"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui2'
         )
      ),
      "GetVolumeDB"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "Channel"=>array(
            "mode"=>'in',
            "default"=>''Master'',
            "allowed"=>'Master|LF|RF',
            "typ"=>'string'
         ),
         "CurrentVolume"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'i2'
         )
      ),
      "SetVolumeDB"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "Channel"=>array(
            "mode"=>'in',
            "default"=>''Master'',
            "allowed"=>'Master|LF|RF',
            "typ"=>'string'
         ),
         "DesiredVolume"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'i2'
         )
      ),
      "GetVolumeDBRange"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "Channel"=>array(
            "mode"=>'in',
            "default"=>''Master'',
            "allowed"=>'Master|LF|RF',
            "typ"=>'string'
         ),
         "MinValue"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'i2'
         ),
         "MaxValue"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'i2'
         )
      ),
      "GetBass"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "CurrentBass"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'i2'
         )
      ),
      "SetBass"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "DesiredBass"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'i2'
         )
      ),
      "GetTreble"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "CurrentTreble"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'i2'
         )
      ),
      "SetTreble"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "DesiredTreble"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'i2'
         )
      ),
      "GetEQ"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "EQType"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "CurrentValue"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'i2'
         )
      ),
      "SetEQ"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "EQType"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "DesiredValue"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'i2'
         )
      ),
      "GetLoudness"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "Channel"=>array(
            "mode"=>'in',
            "default"=>''Master'',
            "allowed"=>'Master|LF|RF',
            "typ"=>'string'
         ),
         "CurrentLoudness"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         )
      ),
      "SetLoudness"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "Channel"=>array(
            "mode"=>'in',
            "default"=>''Master'',
            "allowed"=>'Master|LF|RF',
            "typ"=>'string'
         ),
         "DesiredLoudness"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         )
      ),
      "GetSupportsOutputFixed"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "CurrentSupportsFixed"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         )
      ),
      "GetOutputFixed"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "CurrentFixed"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         )
      ),
      "SetOutputFixed"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "DesiredFixed"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         )
      ),
      "GetHeadphoneConnected"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "CurrentHeadphoneConnected"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         )
      ),
      "RampToVolume"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "Channel"=>array(
            "mode"=>'in',
            "default"=>''Master'',
            "allowed"=>'Master|LF|RF',
            "typ"=>'string'
         ),
         "RampType"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>'SLEEP_TIMER_RAMP_TYPE|ALARM_RAMP_TYPE|AUTOPLAY_RAMP_TYPE',
            "typ"=>'string'
         ),
         "DesiredVolume"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui2'
         ),
         "ResetVolumeAfter"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         ),
         "ProgramURI"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "RampTime"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         )
      ),
      "RestoreVolumePriorToRamp"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "Channel"=>array(
            "mode"=>'in',
            "default"=>''Master'',
            "allowed"=>'Master|LF|RF',
            "typ"=>'string'
         )
      ),
      "SetChannelMap"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "ChannelMap"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      )
   ),
   "AVTransport"=>array(
      "SetAVTransportURI"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "CurrentURI"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "CurrentURIMetaData"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "SetNextAVTransportURI"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "NextURI"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "NextURIMetaData"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "AddURIToQueue"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "EnqueuedURI"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "EnqueuedURIMetaData"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "DesiredFirstTrackNumberEnqueued"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "EnqueueAsNext"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         ),
         "FirstTrackNumberEnqueued"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "NumTracksAdded"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "NewQueueLength"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         )
      ),
      "AddMultipleURIsToQueue"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "UpdateID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "NumberOfURIs"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "EnqueuedURIs"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "EnqueuedURIsMetaData"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "ContainerURI"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "ContainerMetaData"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "DesiredFirstTrackNumberEnqueued"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "EnqueueAsNext"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         ),
         "FirstTrackNumberEnqueued"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "NumTracksAdded"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "NewQueueLength"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "NewUpdateID"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         )
      ),
      "ReorderTracksInQueue"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "StartingIndex"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "NumberOfTracks"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "InsertBefore"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "UpdateID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         )
      ),
      "RemoveTrackFromQueue"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "ObjectID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "UpdateID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         )
      ),
      "RemoveTrackRangeFromQueue"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "UpdateID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "StartingIndex"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "NumberOfTracks"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "NewUpdateID"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         )
      ),
      "RemoveAllTracksFromQueue"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         )
      ),
      "SaveQueue"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "Title"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "ObjectID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "AssignedObjectID"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "BackupQueue"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         )
      ),
      "CreateSavedQueue"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "Title"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "EnqueuedURI"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "EnqueuedURIMetaData"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "NumTracksAdded"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "NewQueueLength"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "AssignedObjectID"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "NewUpdateID"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         )
      ),
      "AddURIToSavedQueue"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "ObjectID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "UpdateID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "EnqueuedURI"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "EnqueuedURIMetaData"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "AddAtIndex"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "NumTracksAdded"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "NewQueueLength"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "NewUpdateID"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         )
      ),
      "ReorderTracksInSavedQueue"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "ObjectID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "UpdateID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "TrackList"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "NewPositionList"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "QueueLengthChange"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'i4'
         ),
         "NewQueueLength"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "NewUpdateID"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         )
      ),
      "GetMediaInfo"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "NrTracks"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "MediaDuration"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "CurrentURI"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "CurrentURIMetaData"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "NextURI"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "NextURIMetaData"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "PlayMedium"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>'NONE|NETWORK',
            "typ"=>'string'
         ),
         "RecordMedium"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>'NONE',
            "typ"=>'string'
         ),
         "WriteStatus"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "GetTransportInfo"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "CurrentTransportState"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>'STOPPED|PLAYING|PAUSED_PLAYBACK|TRANSITIONING',
            "typ"=>'string'
         ),
         "CurrentTransportStatus"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "CurrentSpeed"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>'1',
            "typ"=>'string'
         )
      ),
      "GetPositionInfo"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "Track"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "TrackDuration"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "TrackMetaData"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "TrackURI"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "RelTime"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "AbsTime"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "RelCount"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'i4'
         ),
         "AbsCount"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'i4'
         )
      ),
      "GetDeviceCapabilities"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "PlayMedia"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "RecMedia"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "RecQualityModes"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "GetTransportSettings"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "PlayMode"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>'NORMAL|REPEAT_ALL|SHUFFLE_NOREPEAT|SHUFFLE',
            "typ"=>'string'
         ),
         "RecQualityMode"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "GetCrossfadeMode"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "CrossfadeMode"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         )
      ),
      "Stop"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         )
      ),
      "Play"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "Speed"=>array(
            "mode"=>'in',
            "default"=>1,
            "allowed"=>'1',
            "typ"=>'string'
         )
      ),
      "Pause"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         )
      ),
      "Seek"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "Unit"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>'TRACK_NR|REL_TIME|SECTION',
            "typ"=>'string'
         ),
         "Target"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "Next"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         )
      ),
      "NextProgrammedRadioTracks"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         )
      ),
      "Previous"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         )
      ),
      "NextSection"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         )
      ),
      "PreviousSection"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         )
      ),
      "SetPlayMode"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "NewPlayMode"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>'NORMAL|REPEAT_ALL|SHUFFLE_NOREPEAT|SHUFFLE',
            "typ"=>'string'
         )
      ),
      "SetCrossfadeMode"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "CrossfadeMode"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         )
      ),
      "NotifyDeletedURI"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "DeletedURI"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "GetCurrentTransportActions"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "Actions"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "BecomeCoordinatorOfStandaloneGroup"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         )
      ),
      "DelegateGroupCoordinationTo"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "NewCoordinator"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "RejoinGroup"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         )
      ),
      "BecomeGroupCoordinator"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "CurrentCoordinator"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "CurrentGroupID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "OtherMembers"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "TransportSettings"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "CurrentURI"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "CurrentURIMetaData"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "SleepTimerState"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "AlarmState"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "StreamRestartState"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "CurrentQueueTrackList"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "BecomeGroupCoordinatorAndSource"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "CurrentCoordinator"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "CurrentGroupID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "OtherMembers"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "CurrentURI"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "CurrentURIMetaData"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "SleepTimerState"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "AlarmState"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "StreamRestartState"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "CurrentAVTTrackList"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "CurrentQueueTrackList"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "CurrentSourceState"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "ResumePlayback"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         )
      ),
      "ChangeCoordinator"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "CurrentCoordinator"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "NewCoordinator"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "NewTransportSettings"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "ChangeTransportSettings"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "NewTransportSettings"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "CurrentAVTransportURI"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "ConfigureSleepTimer"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "NewSleepTimerDuration"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "GetRemainingSleepTimerDuration"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "RemainingSleepTimerDuration"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "CurrentSleepTimerGeneration"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         )
      ),
      "RunAlarm"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "AlarmID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "LoggedStartTime"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "Duration"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "ProgramURI"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "ProgramMetaData"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "PlayMode"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>'NORMAL|REPEAT_ALL|SHUFFLE_NOREPEAT|SHUFFLE',
            "typ"=>'string'
         ),
         "Volume"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui2'
         ),
         "IncludeLinkedZones"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         )
      ),
      "StartAutoplay"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "ProgramURI"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "ProgramMetaData"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "Volume"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui2'
         ),
         "IncludeLinkedZones"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         ),
         "ResetVolumeAfter"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         )
      ),
      "GetRunningAlarmProperties"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "AlarmID"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "GroupID"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "LoggedStartTime"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "SnoozeAlarm"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "Duration"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      )
   ),
   "Queue"=>array(
      "AddURI"=>array(
         "QueueID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "UpdateID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "EnqueuedURI"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "EnqueuedURIMetaData"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "DesiredFirstTrackNumberEnqueued"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "EnqueueAsNext"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         ),
         "FirstTrackNumberEnqueued"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "NumTracksAdded"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "NewQueueLength"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "NewUpdateID"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         )
      ),
      "AddMultipleURIs"=>array(
         "QueueID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "UpdateID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "ContainerURI"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "ContainerMetaData"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "DesiredFirstTrackNumberEnqueued"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "EnqueueAsNext"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         ),
         "NumberOfURIs"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "EnqueuedURIsAndMetaData"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "FirstTrackNumberEnqueued"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "NumTracksAdded"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "NewQueueLength"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "NewUpdateID"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         )
      ),
      "AttachQueue"=>array(
         "QueueOwnerID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "QueueID"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "QueueOwnerContext"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "Backup"=>null,
      "Browse"=>array(
         "QueueID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "StartingIndex"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "RequestedCount"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "Result"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "NumberReturned"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "TotalMatches"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "UpdateID"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         )
      ),
      "CreateQueue"=>array(
         "QueueOwnerID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "QueueOwnerContext"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "QueueID"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "QueuePolicy"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "RemoveAllTracks"=>array(
         "QueueID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "UpdateID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "NewUpdateID"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         )
      ),
      "RemoveTrackRange"=>array(
         "QueueID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "UpdateID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "StartingIndex"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "NumberOfTracks"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "NewUpdateID"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         )
      ),
      "ReorderTracks"=>array(
         "QueueID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "StartingIndex"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "NumberOfTracks"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "InsertBefore"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "UpdateID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "NewUpdateID"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         )
      ),
      "ReplaceAllTracks"=>array(
         "QueueID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "UpdateID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "ContainerURI"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "ContainerMetaData"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "CurrentTrackIndex"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "NewCurrentTrackIndices"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "NumberOfURIs"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "EnqueuedURIsAndMetaData"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "NewQueueLength"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "NewUpdateID"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         )
      ),
      "SaveAsSonosPlaylist"=>array(
         "QueueID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "Title"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "ObjectID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "AssignedObjectID"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      )
   ),
   "GroupRenderingControl"=>array(
      "GetGroupMute"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "CurrentMute"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         )
      ),
      "SetGroupMute"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "DesiredMute"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         )
      ),
      "GetGroupVolume"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "CurrentVolume"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui2'
         )
      ),
      "SetGroupVolume"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "DesiredVolume"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui2'
         )
      ),
      "SetRelativeGroupVolume"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "Adjustment"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'i4'
         ),
         "NewVolume"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui2'
         )
      ),
      "SnapshotGroupVolume"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         )
      )
   ),
   "SonosUpnpClass"=>array(
      "__construct"=>array(
         "BASE"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'object'
         ),
         "SERVICE"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "SERVICEURL"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "EVENTURL"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "RegisterEventCallback"=>array(
         "callback_url"=>array(
            "mode"=>'in',
            "default"=>'',
            "allowed"=>null,
            "typ"=>'string'
         ),
         "timeout"=>array(
            "mode"=>'in',
            "default"=>'3600',
            "allowed"=>null,
            "typ"=>'int'
         ),
         "SID"=>array(
            "mode"=>'out',
            "default"=>'',
            "allowed"=>null,
            "typ"=>'string'
         ),
         "TIMEOUT"=>array(
            "mode"=>'out',
            "default"=>'',
            "allowed"=>null,
            "typ"=>'int'
         ),
         "Server"=>array(
            "mode"=>'out',
            "default"=>'',
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "UnRegisterEventCallback"=>array(
         "SID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      )
   ),
   "SonosXmlRpcDevice"=>array(
      "__construct"=>array(
         "url"=>array(
            "mode"=>'in',
            "default"=>'',
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "Upnp"=>array(
         "url"=>array(
            "mode"=>'in',
            "default"=>'',
            "allowed"=>null,
            "typ"=>'string'
         ),
         "SOAP_service"=>array(
            "mode"=>'in',
            "default"=>'',
            "allowed"=>null,
            "typ"=>'string'
         ),
         "SOAP_action"=>array(
            "mode"=>'in',
            "default"=>'',
            "allowed"=>null,
            "typ"=>'string'
         ),
         "SOAP_arguments"=>array(
            "mode"=>'in',
            "default"=>'',
            "allowed"=>null,
            "typ"=>'string'
         ),
         "XML_filter"=>array(
            "mode"=>'in',
            "default"=>'',
            "allowed"=>null,
            "typ"=>'string'
         ),
         "result"=>array(
            "mode"=>'out',
            "default"=>'',
            "allowed"=>null,
            "typ"=>'string|array'
         )
      ),
      "Filter"=>array(
         "subject"=>array(
            "mode"=>'in',
            "default"=>'',
            "allowed"=>null,
            "typ"=>'string'
         ),
         "pattern"=>array(
            "mode"=>'in',
            "default"=>'',
            "allowed"=>null,
            "typ"=>'string|stringlist|array of strings'
         ),
         "result"=>array(
            "mode"=>'out',
            "default"=>'',
            "allowed"=>null,
            "typ"=>'variant'
         )
      )
   )
);
?>