<?
$Samsung_FunctionsVars=array(
   "RenderingControl"=>array(
      "ListPresets"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "CurrentPresetNameList"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "SelectPreset"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "PresetName"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>'FactoryDefaults',
            "typ"=>'string'
         )
      ),
      "GetMute"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "Channel"=>array(
            "mode"=>'in',
            "default"=>''Master'',
            "allowed"=>'Master',
            "typ"=>'string'
         ),
         "CurrentMute"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         )
      ),
      "SetMute"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "Channel"=>array(
            "mode"=>'in',
            "default"=>''Master'',
            "allowed"=>'Master',
            "typ"=>'string'
         ),
         "DesiredMute"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'boolean'
         )
      ),
      "GetVolume"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "Channel"=>array(
            "mode"=>'in',
            "default"=>''Master'',
            "allowed"=>'Master',
            "typ"=>'string'
         ),
         "CurrentVolume"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui2'
         )
      ),
      "SetVolume"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "Channel"=>array(
            "mode"=>'in',
            "default"=>''Master'',
            "allowed"=>'Master',
            "typ"=>'string'
         ),
         "DesiredVolume"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui2'
         )
      ),
      "GetBrightness"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "CurrentBrightness"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui2'
         )
      ),
      "SetBrightness"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "DesiredBrightness"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui2'
         )
      ),
      "GetContrast"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "CurrentContrast"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui2'
         )
      ),
      "SetContrast"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "DesiredContrast"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui2'
         )
      ),
      "GetSharpness"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "CurrentSharpness"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui2'
         )
      ),
      "SetSharpness"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "DesiredSharpness"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui2'
         )
      ),
      "X_UpdateAudioSelection"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "AudioPID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui2'
         ),
         "AudioEncoding"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "X_GetAudioSelection"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "AudioPID"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui2'
         ),
         "AudioEncoding"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "X_UpdateVideoSelection"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "VideoPID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui2'
         ),
         "VideoEncoding"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "X_GetVideoSelection"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "VideoPID"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui2'
         ),
         "VideoEncoding"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      )
   ),
   "ConnectionManager"=>array(
      "GetCurrentConnectionInfo"=>array(
         "ConnectionID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'i4'
         ),
         "RcsID"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'i4'
         ),
         "AVTransportID"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'i4'
         ),
         "ProtocolInfo"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "PeerConnectionManager"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "PeerConnectionID"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'i4'
         ),
         "Direction"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>'Input|Output',
            "typ"=>'string'
         ),
         "Status"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>'OK|ContentFormatMismatch|InsufficientBandwidth|UnreliableChannel|Unknown',
            "typ"=>'string'
         )
      ),
      "GetProtocolInfo"=>array(
         "Source"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "Sink"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "GetCurrentConnectionIDs"=>array(
         "ConnectionIDs"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "PrepareForConnection"=>array(
         "RemoteProtocolInfo"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "PeerConnectionManager"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "PeerConnectionID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'i4'
         ),
         "Direction"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>'Input|Output',
            "typ"=>'string'
         ),
         "ConnectionID"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'i4'
         ),
         "AVTransportID"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'i4'
         ),
         "RcsID"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'i4'
         )
      ),
      "ConnectionComplete"=>array(
         "ConnectionID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'i4'
         )
      )
   ),
   "AVTransport"=>array(
      "Play"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "Speed"=>array(
            "mode"=>'in',
            "default"=>1,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "Stop"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         )
      ),
      "Next"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         )
      ),
      "Previous"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         )
      ),
      "SetPlayMode"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "NewPlayMode"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>'NORMAL',
            "typ"=>'string'
         )
      ),
      "GetMediaInfo"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "NrTracks"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "MediaDuration"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "CurrentURI"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "CurrentURIMetaData"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "NextURI"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "NextURIMetaData"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "PlayMedium"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>'NONE|NETWORK',
            "typ"=>'string'
         ),
         "RecordMedium"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>'NOT_IMPLEMENTED',
            "typ"=>'string'
         ),
         "WriteStatus"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>'NOT_IMPLEMENTED',
            "typ"=>'string'
         )
      ),
      "GetDeviceCapabilities"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "PlayMedia"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "RecMedia"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "RecQualityModes"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "SetAVTransportURI"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "CurrentURI"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "CurrentURIMetaData"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "SetNextAVTransportURI"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "NextURI"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "NextURIMetaData"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "GetTransportSettings"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "PlayMode"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>'NORMAL',
            "typ"=>'string'
         ),
         "RecQualityMode"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>'NOT_IMPLEMENTED',
            "typ"=>'string'
         )
      ),
      "GetTransportInfo"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "CurrentTransportState"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>'STOPPED|PAUSED_PLAYBACK|PLAYING|TRANSITIONING|NO_MEDIA_PRESENT',
            "typ"=>'string'
         ),
         "CurrentTransportStatus"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>'OK|ERROR_OCCURRED',
            "typ"=>'string'
         ),
         "CurrentSpeed"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "Pause"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         )
      ),
      "Seek"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "Unit"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>'TRACK_NR|REL_TIME|ABS_TIME|ABS_COUNT|REL_COUNT|X_DLNA_REL_BYTE|FRAME',
            "typ"=>'string'
         ),
         "Target"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "GetPositionInfo"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "Track"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "TrackDuration"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "TrackMetaData"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "TrackURI"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "RelTime"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "AbsTime"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "RelCount"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'i4'
         ),
         "AbsCount"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'i4'
         )
      ),
      "GetCurrentTransportActions"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "Actions"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "X_DLNA_GetBytePositionInfo"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "TrackSize"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "RelByte"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "AbsByte"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "X_GetStoppedReason"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "StoppedReason"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "StoppedReasonData"=>array(
            "mode"=>'out',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "X_SetAutoSlideShowMode"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "AutoSlideShowMode"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>'ON|OFF',
            "typ"=>'string'
         )
      ),
      "X_SetSlideShowEffectHint"=>array(
         "InstanceID"=>array(
            "mode"=>'in',
            "default"=>0,
            "allowed"=>null,
            "typ"=>'ui4'
         ),
         "SlideShowEffectHint"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>'ON|OFF',
            "typ"=>'string'
         )
      )
   ),
   "SamsungUpnpClass"=>array(
      "__construct"=>array(
         "BASE"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'object'
         ),
         "SERVICE"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "SERVICEURL"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         ),
         "EVENTURL"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "RegisterEventCallback"=>array(
         "callback_url"=>array(
            "mode"=>'in',
            "default"=>'',
            "allowed"=>null,
            "typ"=>'string'
         ),
         "timeout"=>array(
            "mode"=>'in',
            "default"=>'3600',
            "allowed"=>null,
            "typ"=>'int'
         ),
         "SID"=>array(
            "mode"=>'out',
            "default"=>'',
            "allowed"=>null,
            "typ"=>'string'
         ),
         "TIMEOUT"=>array(
            "mode"=>'out',
            "default"=>'',
            "allowed"=>null,
            "typ"=>'int'
         ),
         "Server"=>array(
            "mode"=>'out',
            "default"=>'',
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "UnRegisterEventCallback"=>array(
         "SID"=>array(
            "mode"=>'in',
            "default"=>null,
            "allowed"=>null,
            "typ"=>'string'
         )
      )
   ),
   "SamsungXmlRpcDevice"=>array(
      "__construct"=>array(
         "url"=>array(
            "mode"=>'in',
            "default"=>'',
            "allowed"=>null,
            "typ"=>'string'
         )
      ),
      "Upnp"=>array(
         "url"=>array(
            "mode"=>'in',
            "default"=>'',
            "allowed"=>null,
            "typ"=>'string'
         ),
         "SOAP_service"=>array(
            "mode"=>'in',
            "default"=>'',
            "allowed"=>null,
            "typ"=>'string'
         ),
         "SOAP_action"=>array(
            "mode"=>'in',
            "default"=>'',
            "allowed"=>null,
            "typ"=>'string'
         ),
         "SOAP_arguments"=>array(
            "mode"=>'in',
            "default"=>'',
            "allowed"=>null,
            "typ"=>'string'
         ),
         "XML_filter"=>array(
            "mode"=>'in',
            "default"=>'',
            "allowed"=>null,
            "typ"=>'string'
         ),
         "result"=>array(
            "mode"=>'out',
            "default"=>'',
            "allowed"=>null,
            "typ"=>'string|array'
         )
      ),
      "Filter"=>array(
         "subject"=>array(
            "mode"=>'in',
            "default"=>'',
            "allowed"=>null,
            "typ"=>'string'
         ),
         "pattern"=>array(
            "mode"=>'in',
            "default"=>'',
            "allowed"=>null,
            "typ"=>'string|stringlist|array of strings'
         ),
         "result"=>array(
            "mode"=>'out',
            "default"=>'',
            "allowed"=>null,
            "typ"=>'variant'
         )
      )
   )
);
?>